#!/bin/bash

has_jq=$(which jq)

if [[ -z "$has_jq" ]]; then
    echo "jq not installed"
    exit 1
fi

selected=$(cat ~/memes.json | jq '.[].name' | fzf)

echo "Selected: $selected"

full_json=$(cat ~/memes.json | jq "map(select(.name == $selected))[0]")
id=$(echo $full_json | jq '.id')
base_url=$(echo $full_json | jq '.blank')
n_parts=$(echo $full_json | jq '.lines')

parts=()

for ((i=1;i<=$n_parts;++i)) do
    read -p "Enter phrase #$i: " value
    fixed=$(echo "$value" | sed "s/ /_/g" | sed "s/?/~q/g" | sed "s/%/~p/g" | sed "s/#/~h/g" | tr "[:upper:]" "[:lower:]")
    echo "Got: '$value', fixed to: '$fixed'"
    # parts[i]=$value
    if [[ -z "$fixed" ]]; then
        parts[i]="_"
    else
        parts[i]=$fixed
    fi
done

bare_id=$(echo $id | tr '"' '')
pattern="\(.*$bare_id\)\(\..*\)$"

prefix=$(echo $base_url | sed "s/$pattern/\1/g")
suffix=$(echo $base_url | sed "s/$pattern/\2/g")

core=$(printf "/%s" ${parts[@]})

final_url=$(echo "$prefix$core$suffix" | sed 's/"//g')

echo "Final url: '$final_url'"

